### ISSUE TITLE
approximate times

### ISSUE THREAD

**Issue by audrism** [woc-hack/hackathon-knoxville-2023#1]
It would be good to have approximate times for room reservations: I assume 4 rooms with AV fitting 10 each?

Also, for food breaks? (at least the number)

I also assume video of the room is needed for broadcast to other participants/rooms?

**Comment by alexandernolte** [comment]
I was thinking about starting around 4pm to 5pm on Friday and ending around noon on Sunday. That means we would need food for two lunch breaks and snacks in between. I assume that people will have breakfast in their hotel, but we could, of course, also offer breakfast at the hackathon. For dinner, we could organize something on Friday or Saturday or also leave those free for participants to decide.

Regarding rooms, I would suggest having one larger room that fits all participants and three smaller breakout rooms. All fitted with AC if possible so that remote participants can join. I don't think we need cross-room broadcasting because for the common sessions, we would all be in the larger room.
